package com.scaffold4j.generator;

import com.scaffold4j.model.LLMProvider;
import com.scaffold4j.model.ProjectConfig;
import com.scaffold4j.model.Protocol;

import java.util.List;

/**
 * Generates application.yml and environment-specific configuration files.
 */
public class ConfigGenerator {

    private final ProjectConfig config;

    public ConfigGenerator(ProjectConfig config) {
        this.config = config;
    }

    public String generateMainConfig() {
        StringBuilder sb = new StringBuilder();
        StringBuilder spring = new StringBuilder();
        StringBuilder scaffold4j = new StringBuilder();
        StringBuilder topLevel = new StringBuilder();

        sb.append("""
                # ===========================================================
                # %s — AI Application Configuration
                # Generated by scaffold4j
                # ===========================================================

                """.formatted(config.effectiveArtifactId()));

        spring.append("""
                spring:
                  application:
                    name: %s
                  profiles:
                    active: ${SPRING_PROFILES_ACTIVE:dev}
                """.formatted(config.effectiveArtifactId()));

        spring.append(generateSpringAiProviderProperties());

        // MCP configuration
        if (config.hasProtocol(Protocol.MCP)) {
            if (!config.usesSpringAI()) {
                spring.append("""
                  ai:
                """);
            }
            spring.append("""
                    mcp:
                      server:
                        name: ${MCP_SERVER_NAME:%s}
                        version: ${MCP_SERVER_VERSION:1.0.0}
                        type: SYNC
                        instructions: "You are a helpful AI assistant."
                      client:
                        toolcallback:
                          enabled: true
                    """.formatted(config.effectiveArtifactId()));
        }

        // Database configuration
        if (config.hasDatabase()) {
            spring.append(block(2,
                    "datasource:",
                    "  url: ${DB_URL:" + config.dbType().jdbcUrl(config.dbHost(), config.effectiveDbPort(), config.effectiveDbName()) + "}",
                    "  username: ${DB_USERNAME:" + config.dbUsername() + "}",
                    "  password: ${DB_PASSWORD:" + config.dbPassword() + "}",
                    "  driver-class-name: ${DB_DRIVER:" + config.dbType().driverClassName() + "}",
                    "  hikari:",
                    "    maximum-pool-size: 20",
                    "    minimum-idle: 5",
                    "    idle-timeout: 300000",
                    "    connection-timeout: 20000",
                    "    max-lifetime: 1200000"));

            if (config.usesJpa()) {
                spring.append(indent("""
                jpa:
                    hibernate:
                      ddl-auto: ${JPA_DDL_AUTO:update}
                    show-sql: ${JPA_SHOW_SQL:false}
                    open-in-view: false
                    """, 2));
            }
        }

        // Cache configuration
        if (config.hasCache()) {
            if (config.hasRedisCache()) {
                spring.append(block(2,
                        "cache:",
                        "  type: redis",
                        "  redis:",
                        "    time-to-live: ${CACHE_TTL:3600000}",
                        "    cache-null-values: false",
                        "data:",
                        "  redis:",
                        "    host: ${REDIS_HOST:" + config.redisHost() + "}",
                        "    port: ${REDIS_PORT:" + config.redisPort() + "}",
                        "    password: ${REDIS_PASSWORD:" + (config.redisPassword() != null ? config.redisPassword() : "") + "}",
                        "    database: ${REDIS_DATABASE:" + config.redisDatabase() + "}",
                        "    lettuce:",
                        "      pool:",
                        "        max-active: 16",
                        "        max-idle: 8",
                        "        min-idle: 4",
                        "    timeout: 5000ms"));
            }

            if (config.hasCaffeineCache()) {
                spring.append(block(2,
                        "cache:",
                        "  type: caffeine",
                        "  caffeine:",
                        "    spec: maximumSize=500,expireAfterAccess=600s"));
            }
        }

        // Nacos configuration
        if (config.hasNacos()) {
          spring.append(block(2, "cloud:", "  nacos:"));

            if (config.hasNacosDiscovery()) {
            spring.append(block(6,
                "discovery:",
                "  enabled: true",
                "  server-addr: ${NACOS_ADDR:" + config.nacosAddr() + "}",
                "  namespace: ${NACOS_NAMESPACE:" + config.nacosNamespace() + "}",
                "  group: ${NACOS_GROUP:DEFAULT_GROUP}",
                "  metadata:",
                "    version: ${APP_VERSION:1.0.0}"));
            }

            if (config.hasNacosConfig()) {
            spring.append(block(6,
                "config:",
                "  enabled: true",
                "  server-addr: ${NACOS_ADDR:" + config.nacosAddr() + "}",
                "  namespace: ${NACOS_NAMESPACE:" + config.nacosNamespace() + "}",
                "  group: ${NACOS_GROUP:DEFAULT_GROUP}",
                "  file-extension: yaml",
                "  refresh-enabled: true",
                "  shared-configs:",
                "    - data-id: common.yaml",
                "      group: DEFAULT_GROUP",
                "      refresh: true"));
            }
        }

        // MQ Spring configuration
        if (config.hasMq()) {
            switch (config.mqType()) {
                case RABBITMQ:
                spring.append(block(2,
                    "rabbitmq:",
                    "  host: ${RABBITMQ_HOST:" + config.mqHost() + "}",
                    "  port: ${RABBITMQ_PORT:" + config.effectiveMqPort() + "}",
                    "  username: ${RABBITMQ_USERNAME:" + config.mqUsername() + "}",
                    "  password: ${RABBITMQ_PASSWORD:" + config.mqPassword() + "}",
                    "  virtual-host: ${RABBITMQ_VIRTUAL_HOST:" + config.mqVirtualHost() + "}",
                    "  listener:",
                    "    simple:",
                    "      concurrency: 4",
                    "      max-concurrency: 10",
                    "      prefetch: 10"));
                    break;
                case KAFKA:
                    spring.append(block(2,
                            "kafka:",
                            "  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:" + config.mqHost() + ":" + config.effectiveMqPort() + "}",
                            "  producer:",
                            "    key-serializer: org.apache.kafka.common.serialization.StringSerializer",
                            "    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer",
                            "  consumer:",
                            "    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer",
                            "    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer",
                            "    group-id: " + config.mqGroup(),
                            "    properties:",
                            "      spring.json.trusted.packages: \"*\"",
                            "  listener:",
                            "    concurrency: 4"));
                    break;
                default:
                    break;
            }
        }

        scaffold4j.append("""
                scaffold4j:
                  ai:
                    default-provider: ${AI_DEFAULT_PROVIDER:%s}
                    framework: %s
                    providers:
                """.formatted(config.llmProviders().iterator().next().id(), config.aiFramework().name()));
        for (LLMProvider provider : config.llmProviders()) {
            scaffold4j.append(generateProviderSection(provider));
        }

        // RAG config
        if (config.hasFeature(com.scaffold4j.model.Feature.RAG)) {
            scaffold4j.append(block(4,
                    "rag:",
                    "  enabled: ${RAG_ENABLED:true}",
                    "  vector-store:",
                    "    type: " + config.vectorStore().id(),
                    "  embedding:",
                    "    provider: ${EMBEDDING_PROVIDER:" + config.llmProviders().iterator().next().id() + "}",
                    "  chunking:",
                    "    max-size: 1000",
                    "    overlap: 200"));
        }

        // Memory config
        if (config.hasFeature(com.scaffold4j.model.Feature.MEMORY)) {
          scaffold4j.append(block(4,
              "memory:",
              "  enabled: ${MEMORY_ENABLED:true}",
              "  type: ${MEMORY_TYPE:token-window}",
              "  token-window:",
              "    max-tokens: 4000",
              "  message-window:",
              "    max-messages: 20"));
        }

        // Agent configuration
        scaffold4j.append(block(4,
            "agent:",
            "  mode: ${AGENT_MODE:react}",
            "  max-iterations: 10",
            "  tool-calling:",
            "    enabled: true"));

        if (config.hasFeature(com.scaffold4j.model.Feature.WEBSOCKET)) {
          scaffold4j.append(block(2,
              "websocket:",
              "  endpoint: /ws/chat",
              "  allowed-origins: \"*\"",
              "  max-session-idle: 30m",
              "  max-text-message-size: 8192"));
        }

        if (config.hasMq()) {
          scaffold4j.append(block(2,
              "mq:",
              "  type: " + config.mqType().id(),
              "  request-queue: ai.requests",
              "  response-queue: ai.responses",
              "  consumer-group: " + config.mqGroup()));

            if (config.mqType() == com.scaffold4j.model.MqType.ROCKETMQ) {
                topLevel.append("""
                rocketmq:
                  name-server: ${ROCKETMQ_NAMESRV:%s:%d}
                  producer:
                    group: ${ROCKETMQ_PRODUCER_GROUP:scaffold4j-producer}
                    send-message-timeout: 3000
                """.formatted(config.mqHost(), config.effectiveMqPort()));
            }
        }

        if (config.hasDatabase()) {
            if (config.usesMyBatisPlus()) {
                topLevel.append("""
                mybatis-plus:
                  mapper-locations: classpath*:/mapper/**/*.xml
                  global-config:
                    db-config:
                      id-type: assign_id
                      logic-delete-field: deleted
                      logic-delete-value: 1
                      logic-not-delete-value: 0
                  configuration:
                    map-underscore-to-camel-case: true
                    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
                """);
            }
        }

        // Logging
        topLevel.append("""
                logging:
                  level:
                    root: INFO
                    %s: DEBUG
                    org.springframework.ai: DEBUG
                """.formatted(config.basePackage()));

        sb.append(spring).append("\n");
        sb.append("""
                server:
                  port: ${SERVER_PORT:8080}

                """);
        sb.append(scaffold4j).append("\n");
        sb.append(topLevel);
        return sb.toString();
    }

    private String generateProviderSection(LLMProvider provider) {
        String envPrefix = envPrefix(provider);
        StringBuilder sb = new StringBuilder();
        sb.append("      ").append(provider.id()).append(":\n");
        sb.append("        api-key: ${")
                .append(provider.envVar() != null ? provider.envVar() : envPrefix + "_API_KEY")
                .append("}\n");
        sb.append("        base-url: ${")
                .append(envPrefix)
                .append("_BASE_URL:")
                .append(defaultBaseUrl(provider))
                .append("}\n");

        if (provider == LLMProvider.AZURE_OPENAI) {
            sb.append("        api-version: ${AZURE_OPENAI_API_VERSION:2024-10-21}\n");
        }

        sb.append("        chat:\n");
        sb.append("          model: ${").append(envPrefix).append("_CHAT_MODEL:").append(defaultModel(provider)).append("}\n");
        sb.append("          temperature: 0.7\n");
        sb.append("          max-tokens: 4096\n");

        if (provider == LLMProvider.OPENAI) {
            sb.append("        embedding:\n");
            sb.append("          model: ${").append(envPrefix).append("_EMBEDDING_MODEL:text-embedding-3-small}\n");
        }

        return sb.toString();
    }

    private String generateSpringAiProviderProperties() {
        if (!config.usesSpringAI()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("  ai:\n");
        for (LLMProvider provider : config.llmProviders()) {
            if (!provider.hasSpringAiSupport()) {
                continue;
            }
            sb.append(indent(generateSpringAiProviderSection(provider), 4));
        }
        return sb.toString();
    }

    private String indent(String text, int spaces) {
        String prefix = " ".repeat(spaces);
        String normalized = stripCommonIndent(text);
        StringBuilder sb = new StringBuilder();
        for (String line : normalized.split("\n", -1)) {
            if (!line.isEmpty()) {
                sb.append(prefix).append(line);
            }
            sb.append('\n');
        }
        return sb.toString();
    }

    private String stripCommonIndent(String text) {
        String[] lines = text.stripTrailing().split("\n", -1);
        int min = Integer.MAX_VALUE;
        for (String line : lines) {
            if (line.isBlank()) {
                continue;
            }
            int count = 0;
            while (count < line.length() && line.charAt(count) == ' ') {
                count++;
            }
            min = Math.min(min, count);
        }
        if (min == Integer.MAX_VALUE || min == 0) {
            return text.stripTrailing();
        }
        StringBuilder sb = new StringBuilder();
        for (String line : lines) {
            if (line.length() >= min) {
                sb.append(line.substring(min));
            } else {
                sb.append(line.stripLeading());
            }
            sb.append('\n');
        }
        return sb.toString().stripTrailing();
    }

    private String block(int spaces, String... lines) {
        String prefix = " ".repeat(spaces);
        StringBuilder sb = new StringBuilder();
        for (String line : lines) {
            if (line == null || line.isEmpty()) {
                sb.append('\n');
            } else {
                sb.append(prefix).append(line).append('\n');
            }
        }
        return sb.toString();
    }

    private String generateSpringAiProviderSection(LLMProvider provider) {
        String envPrefix = envPrefix(provider);
        String baseUrl = defaultBaseUrl(provider);
        String model = defaultModel(provider);
        return switch (provider) {
            case OPENAI -> """
                    openai:
                      api-key: ${OPENAI_API_KEY}
                      base-url: ${OPENAI_BASE_URL:%s}
                      chat:
                        options:
                          model: ${OPENAI_CHAT_MODEL:%s}
                          temperature: 0.7
                          max-tokens: 4096
                """.formatted(baseUrl, model);
            case OLLAMA -> """
                    ollama:
                      base-url: ${OLLAMA_BASE_URL:%s}
                      chat:
                        options:
                          model: ${OLLAMA_CHAT_MODEL:%s}
                          temperature: 0.7
                """.formatted(baseUrl, model);
            case ANTHROPIC -> """
                    anthropic:
                      api-key: ${ANTHROPIC_API_KEY}
                      base-url: ${ANTHROPIC_BASE_URL:%s}
                      chat:
                        options:
                          model: ${ANTHROPIC_CHAT_MODEL:%s}
                          temperature: 0.7
                          max-tokens: 4096
                """.formatted(baseUrl, model);
            case AZURE_OPENAI -> """
                    azure:
                      openai:
                        api-key: ${AZURE_OPENAI_API_KEY}
                        endpoint: ${AZURE_OPENAI_BASE_URL:%s}
                        chat:
                          options:
                            deployment-name: ${AZURE_OPENAI_CHAT_MODEL:%s}
                            temperature: 0.7
                            max-tokens: 4096
                """.formatted(baseUrl, model);
            default -> """
                    %s:
                      api-key: ${%s}
                      base-url: ${%s_BASE_URL:%s}
                      chat:
                        options:
                          model: ${%s_CHAT_MODEL:%s}
                          temperature: 0.7
                          max-tokens: 4096
                """.formatted(provider.id(), provider.envVar() != null ? provider.envVar() : envPrefix + "_API_KEY",
                    envPrefix, baseUrl, envPrefix, model);
        };
    }

    private String envPrefix(LLMProvider provider) {
        return provider.id().toUpperCase().replace('-', '_');
    }

    private String defaultBaseUrl(LLMProvider provider) {
        return switch (provider) {
            case OPENAI -> "https://api.openai.com";
            case OLLAMA -> "http://localhost:11434";
            case ANTHROPIC -> "https://api.anthropic.com";
            case DEEPSEEK -> "https://api.deepseek.com";
            case ZHIPUAI -> "https://open.bigmodel.cn/api/paas";
            case VERTEX_AI -> "https://generativelanguage.googleapis.com/v1beta";
            case AZURE_OPENAI -> "https://YOUR_RESOURCE.openai.azure.com";
            case BEDROCK -> "https://bedrock-runtime.us-east-1.amazonaws.com";
            case QWEN -> "https://dashscope.aliyuncs.com/compatible-mode";
            case MOONSHOT -> "https://api.moonshot.cn";
            case DOUBAO -> "https://ark.cn-beijing.volces.com/api";
        };
    }

    private String defaultModel(LLMProvider provider) {
        return switch (provider) {
            case OPENAI -> "gpt-4o";
            case ANTHROPIC -> "claude-sonnet-4-6";
            case OLLAMA -> "llama3.1";
            case DEEPSEEK -> "deepseek-chat";
            case ZHIPUAI -> "glm-4-flash";
            case VERTEX_AI -> "gemini-2.5-flash";
            case AZURE_OPENAI -> "gpt-4o";
            case BEDROCK -> "anthropic.claude-3-5-sonnet-20240620-v1:0";
            case QWEN -> "qwen-plus";
            case MOONSHOT -> "moonshot-v1-8k";
            case DOUBAO -> "doubao-lite-128k";
        };
    }

    /**
     * Generate bootstrap.yml for Nacos Config Center.
     * Loaded before application.yml to connect to Nacos for config import.
     */
    public String generateBootstrapConfig() {
        return """
                # ===========================================================
                # Bootstrap configuration — loaded before application.yml
                # Required for Spring Cloud Config / Nacos Config Center
                # ===========================================================
                spring:
                  application:
                    name: %s
                  cloud:
                    nacos:
                      config:
                        server-addr: ${NACOS_ADDR:%s}
                        namespace: ${NACOS_NAMESPACE:%s}
                        file-extension: yaml
                        group: ${NACOS_GROUP:DEFAULT_GROUP}
                """.formatted(config.effectiveArtifactId(), config.nacosAddr(), config.nacosNamespace());
    }

    public String generateDevConfig() {
        return """
                # Development environment configuration
                spring:
                  ai:
                    mcp:
                      server:
                        version: 1.0.0-dev

                logging:
                  level:
                    root: DEBUG
                """;
    }

    public String generateProdConfig() {
        return """
                # Production environment configuration
                logging:
                  level:
                    root: WARN
                    %s: INFO
                """.formatted(config.basePackage());
    }

    public String generateLogbackConfig() {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <configuration>
                    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
                    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

                    <root level="INFO">
                        <appender-ref ref="CONSOLE"/>
                    </root>

                    <logger name="%s" level="DEBUG"/>
                    <logger name="org.springframework.ai" level="DEBUG"/>
                </configuration>
                """.formatted(config.basePackage());
    }
}
