package com.scaffold4j.generator;

import com.scaffold4j.model.LLMProvider;
import com.scaffold4j.model.ProjectConfig;
import com.scaffold4j.model.Protocol;

import java.util.List;

/**
 * Generates application.yml and environment-specific configuration files.
 */
public class ConfigGenerator {

    private final ProjectConfig config;

    public ConfigGenerator(ProjectConfig config) {
        this.config = config;
    }

    public String generateMainConfig() {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                # ===========================================================
                # %s — AI Application Configuration
                # Generated by scaffold4j
                # ===========================================================

                spring:
                  application:
                    name: %s
                  profiles:
                    active: ${SPRING_PROFILES_ACTIVE:dev}

                server:
                  port: ${SERVER_PORT:8080}

                # ===========================================================
                # scaffold4j AI Configuration
                # ===========================================================
                scaffold4j:
                  ai:
                    default-provider: ${AI_DEFAULT_PROVIDER:%s}
                    framework: %s
                """
                .formatted(
                    config.effectiveArtifactId(),
                    config.effectiveArtifactId(),
                    config.llmProviders().iterator().next().id(),
                    config.aiFramework().name()
                ));

        // LLM Provider configurations
        sb.append("""
                    providers:
                """);
        for (LLMProvider provider : config.llmProviders()) {
            sb.append(generateProviderSection(provider));
        }

        // RAG config
        if (config.hasFeature(com.scaffold4j.model.Feature.RAG)) {
            sb.append("""
                        rag:
                          enabled: ${RAG_ENABLED:true}
                          vector-store:
                            type: %s
                          embedding:
                            provider: ${EMBEDDING_PROVIDER:%s}
                          chunking:
                            max-size: 1000
                            overlap: 200
                    """.formatted(
                        config.vectorStore().id(),
                        config.llmProviders().iterator().next().id()
                    ));
        }

        // Memory config
        if (config.hasFeature(com.scaffold4j.model.Feature.MEMORY)) {
            sb.append("""
                        memory:
                          enabled: ${MEMORY_ENABLED:true}
                          type: ${MEMORY_TYPE:token-window}
                          token-window:
                            max-tokens: 4000
                          message-window:
                            max-messages: 20
                    """);
        }

        // Agent configuration
        sb.append("""
                        agent:
                          mode: ${AGENT_MODE:react}
                          max-iterations: 10
                          tool-calling:
                            enabled: true
                """);

        // MCP configuration
        if (config.hasProtocol(Protocol.MCP)) {
            sb.append("""
                    # ===========================================================
                    # MCP (Model Context Protocol)
                    # ===========================================================
                    spring:
                      ai:
                        mcp:
                          server:
                            name: ${MCP_SERVER_NAME:%s}
                            version: ${MCP_SERVER_VERSION:1.0.0}
                            type: SYNC
                            instructions: "You are a helpful AI assistant."
                          client:
                            toolcallback:
                              enabled: true
                    """.formatted(config.effectiveArtifactId()));
        }

        // Nacos configuration
        if (config.nacosEnabled()) {
            sb.append("""
                    # ===========================================================
                    # Nacos Service Discovery & Configuration
                    # ===========================================================
                    spring:
                      cloud:
                        nacos:
                          discovery:
                            enabled: ${NACOS_ENABLED:true}
                            server-addr: ${NACOS_ADDR:%s}
                            namespace: ${NACOS_NAMESPACE:%s}
                            group: ${NACOS_GROUP:DEFAULT_GROUP}
                          config:
                            server-addr: ${NACOS_ADDR:%s}
                            namespace: ${NACOS_NAMESPACE:%s}
                            file-extension: yaml
                            group: ${NACOS_GROUP:DEFAULT_GROUP}
                      config:
                        import: nacos:%s.yaml
                    """.formatted(
                        config.nacosAddr(), config.nacosNamespace(),
                        config.nacosAddr(), config.nacosNamespace(),
                        config.effectiveArtifactId()
                    ));
        }

        // WebSocket configuration
        if (config.hasFeature(com.scaffold4j.model.Feature.WEBSOCKET)) {
            sb.append("""
                    # ===========================================================
                    # WebSocket
                    # ===========================================================
                    scaffold4j:
                      websocket:
                        endpoint: /ws/chat
                        allowed-origins: "*"
                        max-session-idle: 30m
                        max-text-message-size: 8192
                    """);
        }

        // Logging
        sb.append("""
                # ===========================================================
                # Logging
                # ===========================================================
                logging:
                  level:
                    root: INFO
                    %s: DEBUG
                    org.springframework.ai: DEBUG
                """.formatted(config.basePackage()));

        return sb.toString();
    }

    private String generateProviderSection(LLMProvider provider) {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                          %s:
                            api-key: ${%s}
                    """.formatted(provider.id(),
                        provider.envVar() != null ? provider.envVar() : provider.id().toUpperCase() + "_API_KEY"));

        if (provider == LLMProvider.OPENAI || provider == LLMProvider.AZURE_OPENAI) {
            sb.append("""
                                base-url: ${%s_BASE_URL:%s}
                    """.formatted(
                        provider.id().toUpperCase(),
                        provider == LLMProvider.OPENAI ? "https://api.openai.com" : "https://YOUR_RESOURCE.openai.azure.com"
                    ));
        } else if (provider == LLMProvider.OLLAMA) {
            sb.append("""
                                base-url: ${%s_BASE_URL:http://localhost:11434}
                    """.formatted(provider.id().toUpperCase()));
        }

        sb.append("""
                                chat:
                                  model: ${%s_CHAT_MODEL:%s}
                                  temperature: 0.7
                                  max-tokens: 4096
                    """.formatted(
                        provider.id().toUpperCase(),
                        defaultModel(provider)
                    ));

        if (provider == LLMProvider.OPENAI) {
            sb.append("""
                                embedding:
                                  model: ${%s_EMBEDDING_MODEL:text-embedding-3-small}
                    """.formatted(provider.id().toUpperCase()));
        }

        return sb.toString();
    }

    private String defaultModel(LLMProvider provider) {
        return switch (provider) {
            case OPENAI -> "gpt-4o";
            case ANTHROPIC -> "claude-sonnet-4-6";
            case OLLAMA -> "llama3.1";
            case DEEPSEEK -> "deepseek-chat";
            case ZHIPUAI -> "glm-4-flash";
            case VERTEX_AI -> "gemini-2.5-flash";
            case AZURE_OPENAI -> "gpt-4o";
            case BEDROCK -> "anthropic.claude-sonnet-4-6";
            case QWEN -> "qwen-plus";
            case MOONSHOT -> "moonshot-v1-8k";
            case DOUBAO -> "doubao-lite-128k";
        };
    }

    public String generateDevConfig() {
        return """
                # Development environment configuration
                spring:
                  ai:
                    mcp:
                      server:
                        version: 1.0.0-dev

                logging:
                  level:
                    root: DEBUG
                """;
    }

    public String generateProdConfig() {
        return """
                # Production environment configuration
                logging:
                  level:
                    root: WARN
                    %s: INFO
                """.formatted(config.basePackage());
    }

    public String generateLogbackConfig() {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <configuration>
                    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
                    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

                    <root level="INFO">
                        <appender-ref ref="CONSOLE"/>
                    </root>

                    <logger name="%s" level="DEBUG"/>
                    <logger name="org.springframework.ai" level="DEBUG"/>
                </configuration>
                """.formatted(config.basePackage());
    }
}
