package com.scaffold4j.generator;

import com.scaffold4j.model.LLMProvider;
import com.scaffold4j.model.ProjectConfig;
import com.scaffold4j.model.Protocol;

import java.util.List;

/**
 * Generates application.yml and environment-specific configuration files.
 */
public class ConfigGenerator {

    private final ProjectConfig config;

    public ConfigGenerator(ProjectConfig config) {
        this.config = config;
    }

    public String generateMainConfig() {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                # ===========================================================
                # %s — AI Application Configuration
                # Generated by scaffold4j
                # ===========================================================

                spring:
                  application:
                    name: %s
                  profiles:
                    active: ${SPRING_PROFILES_ACTIVE:dev}

                server:
                  port: ${SERVER_PORT:8080}

                # ===========================================================
                # scaffold4j AI Configuration
                # ===========================================================
                scaffold4j:
                  ai:
                    default-provider: ${AI_DEFAULT_PROVIDER:%s}
                    framework: %s
                """
                .formatted(
                    config.effectiveArtifactId(),
                    config.effectiveArtifactId(),
                    config.llmProviders().iterator().next().id(),
                    config.aiFramework().name()
                ));

        // LLM Provider configurations
        sb.append("""
                    providers:
                """);
        for (LLMProvider provider : config.llmProviders()) {
            sb.append(generateProviderSection(provider));
        }

        // RAG config
        if (config.hasFeature(com.scaffold4j.model.Feature.RAG)) {
            sb.append("""
                        rag:
                          enabled: ${RAG_ENABLED:true}
                          vector-store:
                            type: %s
                          embedding:
                            provider: ${EMBEDDING_PROVIDER:%s}
                          chunking:
                            max-size: 1000
                            overlap: 200
                    """.formatted(
                        config.vectorStore().id(),
                        config.llmProviders().iterator().next().id()
                    ));
        }

        // Memory config
        if (config.hasFeature(com.scaffold4j.model.Feature.MEMORY)) {
            sb.append("""
                        memory:
                          enabled: ${MEMORY_ENABLED:true}
                          type: ${MEMORY_TYPE:token-window}
                          token-window:
                            max-tokens: 4000
                          message-window:
                            max-messages: 20
                    """);
        }

        // Agent configuration
        sb.append("""
                        agent:
                          mode: ${AGENT_MODE:react}
                          max-iterations: 10
                          tool-calling:
                            enabled: true
                """);

        // MCP configuration
        if (config.hasProtocol(Protocol.MCP)) {
            sb.append("""
                    # ===========================================================
                    # MCP (Model Context Protocol)
                    # ===========================================================
                    spring:
                      ai:
                        mcp:
                          server:
                            name: ${MCP_SERVER_NAME:%s}
                            version: ${MCP_SERVER_VERSION:1.0.0}
                            type: SYNC
                            instructions: "You are a helpful AI assistant."
                          client:
                            toolcallback:
                              enabled: true
                    """.formatted(config.effectiveArtifactId()));
        }

        // Database configuration
        if (config.hasDatabase()) {
            sb.append("""
                    # ===========================================================
                    # DataSource Configuration
                    # ===========================================================
                    spring:
                      datasource:
                        url: ${DB_URL:%s}
                        username: ${DB_USERNAME:%s}
                        password: ${DB_PASSWORD:%s}
                        driver-class-name: ${DB_DRIVER:%s}
                        hikari:
                          maximum-pool-size: 20
                          minimum-idle: 5
                          idle-timeout: 300000
                          connection-timeout: 20000
                          max-lifetime: 1200000
                    """.formatted(
                        config.dbType().jdbcUrl(config.dbHost(), config.effectiveDbPort(), config.effectiveDbName()),
                        config.dbUsername(),
                        config.dbPassword(),
                        config.dbType().driverClassName()
                    ));

            if (config.usesJpa()) {
                sb.append("""
                          jpa:
                            hibernate:
                              ddl-auto: ${JPA_DDL_AUTO:update}
                            show-sql: ${JPA_SHOW_SQL:false}
                            open-in-view: false
                    """);
            }

            if (config.usesMyBatisPlus()) {
                sb.append("""
                    # ===========================================================
                    # MyBatis-Plus Configuration
                    # ===========================================================
                    mybatis-plus:
                      mapper-locations: classpath*:/mapper/**/*.xml
                      global-config:
                        db-config:
                          id-type: assign_id
                          logic-delete-field: deleted
                          logic-delete-value: 1
                          logic-not-delete-value: 0
                      configuration:
                        map-underscore-to-camel-case: true
                        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
                    """);
            }
        }

        // Cache configuration
        if (config.hasCache()) {
            sb.append("""
                    # ===========================================================
                    # Cache Configuration
                    # ===========================================================
                    spring:
                      cache:
                        type: %s
                """.formatted(config.cacheType().id()));

            if (config.hasRedisCache()) {
                sb.append("""
                          data:
                            redis:
                              host: ${REDIS_HOST:%s}
                              port: ${REDIS_PORT:%d}
                              password: ${REDIS_PASSWORD:%s}
                              database: ${REDIS_DATABASE:%d}
                              lettuce:
                                pool:
                                  max-active: 16
                                  max-idle: 8
                                  min-idle: 4
                              timeout: 5000ms
                        cache:
                          redis:
                            time-to-live: ${CACHE_TTL:3600000}
                            cache-null-values: false
                """.formatted(
                        config.redisHost(),
                        config.redisPort(),
                        config.redisPassword() != null ? config.redisPassword() : "",
                        config.redisDatabase()
                ));
            }

            if (config.hasCaffeineCache()) {
                sb.append("""
                          cache:
                            caffeine:
                              spec: maximumSize=500,expireAfterAccess=600s
                """);
            }
        }

        // Nacos configuration
        if (config.hasNacos()) {
            sb.append("""
                    # ===========================================================
                    # Nacos Service Discovery & Configuration
                    # ===========================================================
                    spring:
                      cloud:
                        nacos:
                """);

            if (config.hasNacosDiscovery()) {
                sb.append("""
                              discovery:
                                enabled: true
                                server-addr: ${NACOS_ADDR:%s}
                                namespace: ${NACOS_NAMESPACE:%s}
                                group: ${NACOS_GROUP:DEFAULT_GROUP}
                                metadata:
                                  version: ${APP_VERSION:1.0.0}
                    """.formatted(config.nacosAddr(), config.nacosNamespace()));
            }

            if (config.hasNacosConfig()) {
                sb.append("""
                              config:
                                enabled: true
                                server-addr: ${NACOS_ADDR:%s}
                                namespace: ${NACOS_NAMESPACE:%s}
                                group: ${NACOS_GROUP:DEFAULT_GROUP}
                                file-extension: yaml
                                refresh-enabled: true
                                shared-configs:
                                  - data-id: common.yaml
                                    group: DEFAULT_GROUP
                                    refresh: true
                    """.formatted(config.nacosAddr(), config.nacosNamespace()));
            }
        }

        // WebSocket configuration
        if (config.hasFeature(com.scaffold4j.model.Feature.WEBSOCKET)) {
            sb.append("""
                    # ===========================================================
                    # WebSocket
                    # ===========================================================
                    scaffold4j:
                      websocket:
                        endpoint: /ws/chat
                        allowed-origins: "*"
                        max-session-idle: 30m
                        max-text-message-size: 8192
                    """);
        }

        // MQ configuration
        if (config.hasMq()) {
            sb.append("""
                    # ===========================================================
                    # Message Queue Configuration
                    # ===========================================================
                    scaffold4j:
                      mq:
                        type: %s
                        request-queue: ai.requests
                        response-queue: ai.responses
                        consumer-group: %s
                    """.formatted(config.mqType().id(), config.mqGroup()));

            switch (config.mqType()) {
                case RABBITMQ:
                    sb.append("""
                            spring:
                              rabbitmq:
                                host: ${RABBITMQ_HOST:%s}
                                port: ${RABBITMQ_PORT:%d}
                                username: ${RABBITMQ_USERNAME:%s}
                                password: ${RABBITMQ_PASSWORD:%s}
                                virtual-host: ${RABBITMQ_VIRTUAL_HOST:%s}
                                listener:
                                  simple:
                                    concurrency: 4
                                    max-concurrency: 10
                                    prefetch: 10
                            """.formatted(
                            config.mqHost(), config.effectiveMqPort(),
                            config.mqUsername(), config.mqPassword(),
                            config.mqVirtualHost()));
                    break;
                case ROCKETMQ:
                    sb.append("""
                            rocketmq:
                              name-server: ${ROCKETMQ_NAMESRV:%s:%d}
                              producer:
                                group: ${ROCKETMQ_PRODUCER_GROUP:scaffold4j-producer}
                                send-message-timeout: 3000
                            """.formatted(config.mqHost(), config.effectiveMqPort()));
                    break;
                case KAFKA:
                    sb.append("""
                            spring:
                              kafka:
                                bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:%s:%d}
                                producer:
                                  key-serializer: org.apache.kafka.common.serialization.StringSerializer
                                  value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
                                consumer:
                                  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                                  value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                                  group-id: %s
                                  properties:
                                    spring.json.trusted.packages: "*"
                                listener:
                                  concurrency: 4
                            """.formatted(config.mqHost(), config.effectiveMqPort(), config.mqGroup()));
                    break;
            }
        }

        // Logging
        sb.append("""
                # ===========================================================
                # Logging
                # ===========================================================
                logging:
                  level:
                    root: INFO
                    %s: DEBUG
                    org.springframework.ai: DEBUG
                """.formatted(config.basePackage()));

        return sb.toString();
    }

    private String generateProviderSection(LLMProvider provider) {
        String envPrefix = envPrefix(provider);
        StringBuilder sb = new StringBuilder();
        sb.append("      ").append(provider.id()).append(":\n");
        sb.append("        api-key: ${")
                .append(provider.envVar() != null ? provider.envVar() : envPrefix + "_API_KEY")
                .append("}\n");
        sb.append("        base-url: ${")
                .append(envPrefix)
                .append("_BASE_URL:")
                .append(defaultBaseUrl(provider))
                .append("}\n");

        if (provider == LLMProvider.AZURE_OPENAI) {
            sb.append("        api-version: ${AZURE_OPENAI_API_VERSION:2024-10-21}\n");
        }

        sb.append("        chat:\n");
        sb.append("          model: ${").append(envPrefix).append("_CHAT_MODEL:").append(defaultModel(provider)).append("}\n");
        sb.append("          temperature: 0.7\n");
        sb.append("          max-tokens: 4096\n");

        if (provider == LLMProvider.OPENAI) {
            sb.append("        embedding:\n");
            sb.append("          model: ${").append(envPrefix).append("_EMBEDDING_MODEL:text-embedding-3-small}\n");
        }

        return sb.toString();
    }

    private String envPrefix(LLMProvider provider) {
        return provider.id().toUpperCase().replace('-', '_');
    }

    private String defaultBaseUrl(LLMProvider provider) {
        return switch (provider) {
            case OPENAI -> "https://api.openai.com";
            case OLLAMA -> "http://localhost:11434";
            case ANTHROPIC -> "https://api.anthropic.com";
            case DEEPSEEK -> "https://api.deepseek.com";
            case ZHIPUAI -> "https://open.bigmodel.cn/api/paas";
            case VERTEX_AI -> "https://generativelanguage.googleapis.com/v1beta";
            case AZURE_OPENAI -> "https://YOUR_RESOURCE.openai.azure.com";
            case BEDROCK -> "https://bedrock-runtime.us-east-1.amazonaws.com";
            case QWEN -> "https://dashscope.aliyuncs.com/compatible-mode";
            case MOONSHOT -> "https://api.moonshot.cn";
            case DOUBAO -> "https://ark.cn-beijing.volces.com/api";
        };
    }

    private String defaultModel(LLMProvider provider) {
        return switch (provider) {
            case OPENAI -> "gpt-4o";
            case ANTHROPIC -> "claude-sonnet-4-6";
            case OLLAMA -> "llama3.1";
            case DEEPSEEK -> "deepseek-chat";
            case ZHIPUAI -> "glm-4-flash";
            case VERTEX_AI -> "gemini-2.5-flash";
            case AZURE_OPENAI -> "gpt-4o";
            case BEDROCK -> "anthropic.claude-3-5-sonnet-20240620-v1:0";
            case QWEN -> "qwen-plus";
            case MOONSHOT -> "moonshot-v1-8k";
            case DOUBAO -> "doubao-lite-128k";
        };
    }

    /**
     * Generate bootstrap.yml for Nacos Config Center.
     * Loaded before application.yml to connect to Nacos for config import.
     */
    public String generateBootstrapConfig() {
        return """
                # ===========================================================
                # Bootstrap configuration — loaded before application.yml
                # Required for Spring Cloud Config / Nacos Config Center
                # ===========================================================
                spring:
                  application:
                    name: %s
                  cloud:
                    nacos:
                      config:
                        server-addr: ${NACOS_ADDR:%s}
                        namespace: ${NACOS_NAMESPACE:%s}
                        file-extension: yaml
                        group: ${NACOS_GROUP:DEFAULT_GROUP}
                """.formatted(config.effectiveArtifactId(), config.nacosAddr(), config.nacosNamespace());
    }

    public String generateDevConfig() {
        return """
                # Development environment configuration
                spring:
                  ai:
                    mcp:
                      server:
                        version: 1.0.0-dev

                logging:
                  level:
                    root: DEBUG
                """;
    }

    public String generateProdConfig() {
        return """
                # Production environment configuration
                logging:
                  level:
                    root: WARN
                    %s: INFO
                """.formatted(config.basePackage());
    }

    public String generateLogbackConfig() {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <configuration>
                    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
                    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

                    <root level="INFO">
                        <appender-ref ref="CONSOLE"/>
                    </root>

                    <logger name="%s" level="DEBUG"/>
                    <logger name="org.springframework.ai" level="DEBUG"/>
                </configuration>
                """.formatted(config.basePackage());
    }
}
