package com.scaffold4j.generator;

import com.scaffold4j.model.DatabaseType;
import com.scaffold4j.model.LLMProvider;
import com.scaffold4j.model.ProjectConfig;
import com.scaffold4j.model.VectorStore;

/**
 * Generates Dockerfile and docker-compose.yml for the project.
 */
public class DockerGenerator {

    private final ProjectConfig config;

    public DockerGenerator(ProjectConfig config) {
        this.config = config;
    }

    public String generateDockerfile() {
        String jarName = config.moduleName("bootstrap");

        StringBuilder sb = new StringBuilder();
        sb.append("""
                # Multi-stage build for Java AI Application
                # Generated by scaffold4j

                FROM eclipse-temurin:%d-jre AS builder
                WORKDIR /app
                """.formatted(config.javaVersion()));

        sb.append("""

                # Copy the built JAR
                COPY %s/target/%s-*.jar app.jar

                # Run the application
                EXPOSE 8080
                ENTRYPOINT ["java", "-jar", "app.jar"]
                """.formatted(jarName, jarName));

        return sb.toString();
    }

    public String generateDockerCompose() {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                version: "3.9"
                services:
                  app:
                    build:
                      context: ..
                      dockerfile: docker/Dockerfile
                    ports:
                      - "${APP_PORT:-8080}:8080"
                    environment:
                      - SPRING_PROFILES_ACTIVE=dev
                """);

        for (LLMProvider provider : config.llmProviders()) {
            String envVar = provider.envVar();
            if (envVar != null) {
                sb.append("      - ").append(envVar).append("=${").append(envVar).append("}\n");
            }
        }

        // Database env vars for docker-compose
        if (config.hasDatabase() && config.dbType() != DatabaseType.H2) {
            sb.append("      - DB_URL=").append(config.dbType().jdbcUrl(
                    config.dbType().id(), config.dbType().defaultPort(), config.effectiveDbName())).append("\n");
            sb.append("      - DB_USERNAME=").append(config.dbUsername()).append("\n");
            sb.append("      - DB_PASSWORD=").append(config.dbPassword()).append("\n");
        }
        if (config.hasRedisCache()) {
            sb.append("      - REDIS_HOST=redis\n");
        }
        if (config.hasNacos()) {
            sb.append("      - NACOS_ADDR=nacos:8848\n");
        }
        if (config.hasMq()) {
            switch (config.mqType()) {
                case RABBITMQ:
                    sb.append("      - RABBITMQ_HOST=rabbitmq\n");
                    break;
                case ROCKETMQ:
                    sb.append("      - ROCKETMQ_NAMESRV=rocketmq:9876\n");
                    break;
                case KAFKA:
                    sb.append("      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092\n");
                    break;
            }
        }

        // depends_on section
        StringBuilder dependsOn = new StringBuilder();
        if (config.hasDatabase() && config.dbType() != DatabaseType.H2) {
            dependsOn.append("        ").append(config.dbType().id()).append(":\n");
            dependsOn.append("          condition: service_healthy\n");
        }
        if (config.hasRedisCache()) {
            dependsOn.append("        redis:\n");
            dependsOn.append("          condition: service_healthy\n");
        }
        if (config.isRabbitMq()) {
            dependsOn.append("        rabbitmq:\n");
            dependsOn.append("          condition: service_healthy\n");
        } else if (config.isKafka()) {
            dependsOn.append("        kafka:\n");
            dependsOn.append("          condition: service_healthy\n");
        } else if (config.isRocketMq()) {
            dependsOn.append("        rocketmq:\n");
            dependsOn.append("          condition: service_started\n");
        }
        if (!dependsOn.isEmpty()) {
            sb.append("    depends_on:\n").append(dependsOn);
        }

        // networks
        boolean hasNetworks = config.hasDatabase() || config.hasRedisCache() || config.hasNacos() || config.hasMq();
        if (hasNetworks) {
            sb.append("    networks:\n      - app-net\n");
        }

        // Ollama local service
        if (config.hasLLMProvider(LLMProvider.OLLAMA)) {
            sb.append("""

                  ollama:
                    image: ollama/ollama:latest
                    ports:
                      - "11434:11434"
                    volumes:
                      - ollama_data:/root/.ollama
                """);
        }

        // Vector store services
        VectorStore vs = config.vectorStore();
        if (vs == VectorStore.PGVECTOR) {
            sb.append("""

                  postgres:
                    image: pgvector/pgvector:pg17
                    environment:
                      POSTGRES_DB: vectordb
                      POSTGRES_USER: postgres
                      POSTGRES_PASSWORD: postgres
                    ports:
                      - "5432:5432"
                    volumes:
                      - pgdata:/var/lib/postgresql/data
                """);
        } else if (vs == VectorStore.REDIS) {
            sb.append("""

                  redis:
                    image: redis/redis-stack:latest
                    ports:
                      - "6379:6379"
                      - "8001:8001"
                """);
        } else if (vs == VectorStore.MILVUS) {
            sb.append("""

                  etcd:
                    image: quay.io/coreos/etcd:v3.5.5
                    environment:
                      ETCD_AUTO_COMPACTION_MODE: revision
                      ETCD_AUTO_COMPACTION_RETENTION: "1000"
                      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
                    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

                  milvus:
                    image: milvusdb/milvus:v2.4.0
                    environment:
                      ETCD_ENDPOINTS: etcd:2379
                    ports:
                      - "19530:19530"
                    depends_on:
                      - etcd
                """);
        } else if (vs == VectorStore.CHROMA) {
            sb.append("""

                  chroma:
                    image: chromadb/chroma:latest
                    ports:
                      - "8000:8000"
                """);
        } else if (vs == VectorStore.ELASTICSEARCH) {
            sb.append("""

                  elasticsearch:
                    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
                    environment:
                      discovery.type: single-node
                      xpack.security.enabled: false
                    ports:
                      - "9200:9200"
                """);
        }

        // Nacos service
        if (config.hasNacos()) {
            sb.append("""

                  nacos:
                    image: nacos/nacos-server:v2.4.0
                    environment:
                      MODE: standalone
                    ports:
                      - "8848:8848"
                      - "9848:9848"
                    volumes:
                      - nacos_data:/home/nacos/data
                """);
            if (hasNetworks) {
                sb.append("    networks:\n      - app-net\n");
            }
        }

        // MQ services
        if (config.isRabbitMq()) {
            sb.append("""

                  rabbitmq:
                    image: rabbitmq:4.0-management-alpine
                    environment:
                      RABBITMQ_DEFAULT_USER: """ + config.mqUsername() + """
                      RABBITMQ_DEFAULT_PASS: """ + config.mqPassword() + """
                    ports:
                      - "5672:5672"
                      - "15672:15672"
                    volumes:
                      - rabbitmq_data:/var/lib/rabbitmq
                    healthcheck:
                      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
                      interval: 10s
                      timeout: 5s
                      retries: 5
                """);
            if (hasNetworks) {
                sb.append("    networks:\n      - app-net\n");
            }
        } else if (config.isRocketMq()) {
            sb.append("""

                  rocketmq:
                    image: apache/rocketmq:5.3.0
                    environment:
                      JAVA_OPT_EXT: "-Xms512m -Xmx512m"
                    ports:
                      - "9876:9876"
                      - "10911:10911"
                      - "10909:10909"
                    volumes:
                      - rocketmq_data:/home/rocketmq
                """);
            if (hasNetworks) {
                sb.append("    networks:\n      - app-net\n");
            }
        } else if (config.isKafka()) {
            sb.append("""

                  zookeeper:
                    image: confluentinc/cp-zookeeper:7.6.0
                    environment:
                      ZOOKEEPER_CLIENT_PORT: 2181
                      ZOOKEEPER_TICK_TIME: 2000
                    ports:
                      - "2181:2181"

                  kafka:
                    image: confluentinc/cp-kafka:7.6.0
                    depends_on:
                      - zookeeper
                    environment:
                      KAFKA_BROKER_ID: 1
                      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
                      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
                      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
                    ports:
                      - "9092:9092"
                    volumes:
                      - kafka_data:/var/lib/kafka/data
                    healthcheck:
                      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
                      interval: 10s
                      timeout: 5s
                      retries: 10
                """);
            if (hasNetworks) {
                sb.append("    networks:\n      - app-net\n");
            }
        }

        // Database service (MySQL or PostgreSQL)
        if (config.hasDatabase() && config.dbType() == DatabaseType.MYSQL) {
            String mysqlSection = """

                  mysql:
                    image: mysql:8.0
                    environment:
                      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
                      MYSQL_DATABASE: ${MYSQL_DB}
                    ports:
                      - "3306:3306"
                    volumes:
                      - mysql_data:/var/lib/mysql
                    healthcheck:
                      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
                      interval: 10s
                      timeout: 5s
                      retries: 5
                """;
            mysqlSection = mysqlSection
                    .replace("${MYSQL_PASS}", config.dbPassword())
                    .replace("${MYSQL_DB}", config.effectiveDbName());
            sb.append(mysqlSection);
            if (hasNetworks) {
                sb.append("    networks:\n      - app-net\n");
            }
        } else if (config.hasDatabase() && config.dbType() == DatabaseType.POSTGRESQL) {
            String pgSection = """

                  postgres:
                    image: postgres:16-alpine
                    environment:
                      POSTGRES_DB: ${PG_DB}
                      POSTGRES_USER: ${PG_USER}
                      POSTGRES_PASSWORD: ${PG_PASS}
                    ports:
                      - "5432:5432"
                    volumes:
                      - pg_data:/var/lib/postgresql/data
                    healthcheck:
                      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
                      interval: 10s
                      timeout: 5s
                      retries: 5
                """;
            pgSection = pgSection
                    .replace("${PG_DB}", config.effectiveDbName())
                    .replace("${PG_USER}", config.dbUsername())
                    .replace("${PG_PASS}", config.dbPassword());
            sb.append(pgSection);
            if (hasNetworks) {
                sb.append("    networks:\n      - app-net\n");
            }
        }

        // Redis cache service (separate from vector-store Redis)
        if (config.hasRedisCache()) {
            String redisCmd = "redis-server --appendonly yes";
            if (config.redisPassword() != null && !config.redisPassword().isBlank()) {
                redisCmd += " --requirepass " + config.redisPassword();
            }
            sb.append("""

                  redis:
                    image: redis:7-alpine
                    command: """ + redisCmd + """
                    ports:
                      - "6379:6379"
                    volumes:
                      - redis_data:/data
                    healthcheck:
                      test: ["CMD", "redis-cli", "ping"]
                      interval: 10s
                      timeout: 5s
                      retries: 5
                """);
            if (hasNetworks) {
                sb.append("    networks:\n      - app-net\n");
            }
        }

        // Volumes
        sb.append("""

                volumes:
                """);
        if (config.hasLLMProvider(LLMProvider.OLLAMA)) {
            sb.append("  ollama_data:\n");
        }
        if (config.vectorStore() == VectorStore.PGVECTOR || config.dbType() == DatabaseType.POSTGRESQL) {
            sb.append("  pg_data:\n");
        }
        if (config.dbType() == DatabaseType.MYSQL) {
            sb.append("  mysql_data:\n");
        }
        if (config.hasRedisCache()) {
            sb.append("  redis_data:\n");
        }
        if (config.hasNacos()) {
            sb.append("  nacos_data:\n");
        }
        if (config.isRabbitMq()) {
            sb.append("  rabbitmq_data:\n");
        }
        if (config.isRocketMq()) {
            sb.append("  rocketmq_data:\n");
        }
        if (config.isKafka()) {
            sb.append("  kafka_data:\n");
        }

        // networks
        if (hasNetworks) {
            sb.append("""

                networks:
                  app-net:
                    driver: bridge
                """);
        }

        return sb.toString();
    }
}
