package com.scaffold4j.generator;

import com.scaffold4j.model.LLMProvider;
import com.scaffold4j.model.ProjectConfig;
import com.scaffold4j.model.VectorStore;

/**
 * Generates Dockerfile and docker-compose.yml for the project.
 */
public class DockerGenerator {

    private final ProjectConfig config;

    public DockerGenerator(ProjectConfig config) {
        this.config = config;
    }

    public String generateDockerfile() {
        String jarName = config.moduleName("bootstrap");

        StringBuilder sb = new StringBuilder();
        sb.append("""
                # Multi-stage build for Java AI Application
                # Generated by scaffold4j

                FROM eclipse-temurin:%d-jre AS builder
                WORKDIR /app
                """.formatted(config.javaVersion()));

        sb.append("""

                # Copy the built JAR
                COPY %s/target/%s-*.jar app.jar

                # Run the application
                EXPOSE 8080
                ENTRYPOINT ["java", "-jar", "app.jar"]
                """.formatted(jarName, jarName));

        return sb.toString();
    }

    public String generateDockerCompose() {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                version: "3.9"
                services:
                  app:
                    build:
                      context: ..
                      dockerfile: docker/Dockerfile
                    ports:
                      - "${APP_PORT:-8080}:8080"
                    environment:
                      - SPRING_PROFILES_ACTIVE=dev
                """);

        for (LLMProvider provider : config.llmProviders()) {
            String envVar = provider.envVar();
            if (envVar != null) {
                sb.append("      - ").append(envVar).append("=${").append(envVar).append("}\n");
            }
        }

        // Ollama local service
        if (config.hasLLMProvider(LLMProvider.OLLAMA)) {
            sb.append("""

                  ollama:
                    image: ollama/ollama:latest
                    ports:
                      - "11434:11434"
                    volumes:
                      - ollama_data:/root/.ollama
                """);
        }

        // Vector store services
        VectorStore vs = config.vectorStore();
        if (vs == VectorStore.PGVECTOR) {
            sb.append("""

                  postgres:
                    image: pgvector/pgvector:pg17
                    environment:
                      POSTGRES_DB: vectordb
                      POSTGRES_USER: postgres
                      POSTGRES_PASSWORD: postgres
                    ports:
                      - "5432:5432"
                    volumes:
                      - pgdata:/var/lib/postgresql/data
                """);
        } else if (vs == VectorStore.REDIS) {
            sb.append("""

                  redis:
                    image: redis/redis-stack:latest
                    ports:
                      - "6379:6379"
                      - "8001:8001"
                """);
        } else if (vs == VectorStore.MILVUS) {
            sb.append("""

                  etcd:
                    image: quay.io/coreos/etcd:v3.5.5
                    environment:
                      ETCD_AUTO_COMPACTION_MODE: revision
                      ETCD_AUTO_COMPACTION_RETENTION: "1000"
                      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
                    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

                  milvus:
                    image: milvusdb/milvus:v2.4.0
                    environment:
                      ETCD_ENDPOINTS: etcd:2379
                    ports:
                      - "19530:19530"
                    depends_on:
                      - etcd
                """);
        } else if (vs == VectorStore.CHROMA) {
            sb.append("""

                  chroma:
                    image: chromadb/chroma:latest
                    ports:
                      - "8000:8000"
                """);
        } else if (vs == VectorStore.ELASTICSEARCH) {
            sb.append("""

                  elasticsearch:
                    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
                    environment:
                      discovery.type: single-node
                      xpack.security.enabled: false
                    ports:
                      - "9200:9200"
                """);
        }

        // Nacos
        if (config.nacosEnabled()) {
            sb.append("""

                  nacos:
                    image: nacos/nacos-server:v2.4.0
                    environment:
                      MODE: standalone
                    ports:
                      - "8848:8848"
                      - "9848:9848"
                """);
        }

        // Volumes
        sb.append("""

                volumes:
                """);
        if (config.hasLLMProvider(LLMProvider.OLLAMA)) {
            sb.append("  ollama_data:\n");
        }
        if (config.vectorStore() == VectorStore.PGVECTOR) {
            sb.append("  pgdata:\n");
        }

        return sb.toString();
    }
}
