package com.scaffold4j.generator;

import com.scaffold4j.model.ProjectConfig;

/**
 * Generates .gitignore and .editorconfig files.
 */
public class GitignoreGenerator {

    @SuppressWarnings("unused")
    private final ProjectConfig config;

    public GitignoreGenerator(ProjectConfig config) {
        this.config = config;
    }

    public String generate() {
        return """
                # ==================================================
                # Generated by scaffold4j
                # ==================================================

                # --- Java / Maven ---
                target/
                *.class
                *.jar
                *.war
                !gradle/wrapper/gradle-wrapper.jar
                .mvn/wrapper/maven-wrapper.jar

                # --- IDE ---
                .idea/
                *.iml
                .vscode/
                .classpath
                .project
                .settings/
                *.swp
                *.swo
                *~

                # --- OS ---
                .DS_Store
                Thumbs.db

                # --- Environment ---
                .env
                .env.local
                .env.*.local
                application-local.yml

                # --- Logs ---
                logs/
                *.log

                # --- AI/LLM ---
                *.gguf
                models/

                # --- Vector Store ---
                chroma_data/
                milvus_data/

                # --- Temp ---
                tmp/
                temp/
                """;
    }

    public String generateEditorConfig() {
        return """
                root = true

                [*]
                charset = utf-8
                end_of_line = lf
                indent_style = space
                indent_size = 4
                insert_final_newline = true
                trim_trailing_whitespace = true

                [*.yml]
                indent_size = 2

                [*.yaml]
                indent_size = 2

                [*.xml]
                indent_size = 2

                [*.md]
                trim_trailing_whitespace = false
                """;
    }
}
