package com.scaffold4j.generator;

import com.scaffold4j.model.AIFramework;
import com.scaffold4j.model.ProjectConfig;
import com.scaffold4j.model.Protocol;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates pom.xml files for the root project and each module.
 */
public class PomGenerator {

    private final ProjectConfig config;

    public PomGenerator(ProjectConfig config) {
        this.config = config;
    }

    /**
     * Generate the root aggregator POM.
     */
    public String generateRootPom() {
        List<String> modules = new ArrayList<>();
        modules.add(config.moduleName("common"));
        modules.add(config.moduleName("domain"));
        modules.add(config.moduleName("infra"));
        modules.add(config.moduleName("app"));
        modules.add(config.moduleName("api"));
        modules.add(config.moduleName("bootstrap"));

        String modulesXml = modules.stream()
                .map(m -> "        <module>" + m + "</module>")
                .collect(Collectors.joining("\n"));

        StringBuilder deps = new StringBuilder();

        // Spring AI BOM
        if (config.usesSpringAI()) {
            deps.append("""
                    <!-- Spring AI BOM -->
                            <dependency>
                                <groupId>org.springframework.ai</groupId>
                                <artifactId>spring-ai-bom</artifactId>
                                <version>${spring-ai.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                    """);
        }

        // LangChain4j BOM
        if (config.usesLangChain4j()) {
            deps.append("""
                    <!-- LangChain4j BOM -->
                            <dependency>
                                <groupId>dev.langchain4j</groupId>
                                <artifactId>langchain4j-bom</artifactId>
                                <version>${langchain4j.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                    """);
        }

        // Nacos BOM
        if (config.nacosEnabled()) {
            deps.append("""
                    <!-- Spring Cloud Alibaba BOM -->
                            <dependency>
                                <groupId>com.alibaba.cloud</groupId>
                                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                                <version>${spring-cloud-alibaba.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                    """);
        }

        // Spring Cloud BOM (needed for Nacos)
        if (config.nacosEnabled()) {
            deps.append("""
                    <!-- Spring Cloud BOM -->
                            <dependency>
                                <groupId>org.springframework.cloud</groupId>
                                <artifactId>spring-cloud-dependencies</artifactId>
                                <version>${spring-cloud.version}</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                    """);
        }

        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                         https://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>

                    <parent>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-parent</artifactId>
                        <version>${spring.boot.version}</version>
                        <relativePath/>
                    </parent>

                    <groupId>${group.id}</groupId>
                    <artifactId>${artifact.id}</artifactId>
                    <version>${version}</version>
                    <packaging>pom</packaging>

                    <name>${project.name}</name>
                    <description>AI Application generated by scaffold4j</description>

                    <modules>
                ${modules}
                    </modules>

                    <properties>
                        <java.version>${java.version}</java.version>
                        <maven.compiler.parameters>true</maven.compiler.parameters>
                        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                ${aiProps()}
                    </properties>

                    <dependencyManagement>
                        <dependencies>
                ${deps}
                        </dependencies>
                    </dependencyManagement>

                    <dependencies>
                        <dependency>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <optional>true</optional>
                        </dependency>
                    </dependencies>

                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <configuration>
                                    <parameters>true</parameters>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """
                .replace("${group.id}", config.effectiveGroupId())
                .replace("${artifact.id}", config.effectiveArtifactId())
                .replace("${version}", config.version())
                .replace("${project.name}", config.name())
                .replace("${spring.boot.version}", config.springBootVersion())
                .replace("${java.version}", String.valueOf(config.javaVersion()))
                .replace("${modules}", modulesXml)
                .replace("${aiProps}", aiProps())
                .replace("${deps}", deps.toString());
    }

    private String aiProps() {
        StringBuilder sb = new StringBuilder();
        sb.append("        <spring-ai.version>1.0.1</spring-ai.version>\n");
        sb.append("        <langchain4j.version>1.0.0-beta1</langchain4j.version>\n");
        if (config.nacosEnabled()) {
            sb.append("        <spring-cloud.version>").append(config.springCloudVersion()).append("</spring-cloud.version>\n");
            sb.append("        <spring-cloud-alibaba.version>2025.0.0.0</spring-cloud-alibaba.version>\n");
        }
        return sb.toString();
    }

    /**
     * Generate a module-level pom.xml.
     * @param moduleDirName e.g. "myapp-common"
     * @param moduleType "common", "domain", "infra", "app", "api", "bootstrap"
     * @param parentModuleName parent dependency (null for common)
     */
    public String generateModulePom(String moduleDirName, String moduleType, String parentModuleName) {
        StringBuilder dependencies = new StringBuilder();

        // Internal module dependency
        if (parentModuleName != null) {
            dependencies.append("""
                    <!-- Internal module -->
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${parent}</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                    """.replace("${parent}", parentModuleName));
        }

        // Module-specific dependencies
        switch (moduleType) {
            case "domain":
                dependencies.append("""
                        <!-- Jakarta Validation -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-validation</artifactId>
                        </dependency>
                        """);
                break;

            case "infra":
                dependencies.append("""
                        <!-- Spring Boot Starter -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter</artifactId>
                        </dependency>
                        """);

                // Spring AI starters for each LLM provider
                if (config.usesSpringAI()) {
                    for (var provider : config.llmProviders()) {
                        if (provider.hasSpringAiSupport()) {
                            dependencies.append("""
                                    <dependency>
                                        <groupId>org.springframework.ai</groupId>
                                        <artifactId>""" + provider.springAiStarter() + """
                                    </artifactId>
                                    </dependency>
                                    """);
                        }
                    }
                    if (!config.llmProviders().isEmpty()) {
                        dependencies.append("""
                                <dependency>
                                    <groupId>org.springframework.ai</groupId>
                                    <artifactId>spring-ai-client-chat</artifactId>
                                </dependency>
                                """);
                    }
                }

                // LangChain4j dependencies
                if (config.usesLangChain4j()) {
                    dependencies.append("""
                            <dependency>
                                <groupId>dev.langchain4j</groupId>
                                <artifactId>langchain4j</artifactId>
                            </dependency>
                            """);
                    for (var provider : config.llmProviders()) {
                        if (provider.hasLangchain4jSupport()) {
                            dependencies.append("""
                                    <dependency>
                                        <groupId>dev.langchain4j</groupId>
                                        <artifactId>""" + provider.langchain4jModule() + """
                                    </artifactId>
                                    </dependency>
                                    """);
                        }
                    }
                }

                // Vector store dependency
                if (config.usesSpringAI() && config.vectorStore().springAiStarter() != null) {
                    dependencies.append("""
                            <dependency>
                                <groupId>org.springframework.ai</groupId>
                                <artifactId>""" + config.vectorStore().springAiStarter() + """
                            </artifactId>
                            </dependency>
                            """);
                }

                // Nacos
                if (config.nacosEnabled()) {
                    dependencies.append("""
                            <!-- Nacos Discovery -->
                            <dependency>
                                <groupId>com.alibaba.cloud</groupId>
                                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                            </dependency>
                            """);
                }

                // WebSocket
                if (config.hasFeature(com.scaffold4j.model.Feature.WEBSOCKET)) {
                    dependencies.append("""
                            <!-- WebSocket -->
                            <dependency>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-starter-websocket</artifactId>
                            </dependency>
                            """);
                }
                break;

            case "app":
                dependencies.append("""
                        <!-- Spring Context -->
                        <dependency>
                            <groupId>org.springframework</groupId>
                            <artifactId>spring-context</artifactId>
                        </dependency>
                        """);

                if (config.usesLangChain4j()) {
                    dependencies.append("""
                            <!-- LangGraph4j for Agent Workflow -->
                            <dependency>
                                <groupId>org.bsc.langgraph4j</groupId>
                                <artifactId>langgraph4j-core</artifactId>
                                <version>1.2.3</version>
                            </dependency>
                            """);
                }
                break;

            case "api":
                dependencies.append("""
                        <!-- Spring Web MVC -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-web</artifactId>
                        </dependency>
                        <!-- Spring WebFlux (for reactive streaming) -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-webflux</artifactId>
                        </dependency>
                        """);

                // MCP dependencies
                if (config.hasProtocol(Protocol.MCP) && config.usesSpringAI()) {
                    dependencies.append("""
                            <!-- MCP Server -->
                            <dependency>
                                <groupId>org.springframework.ai</groupId>
                                <artifactId>spring-ai-starter-mcp-server-webmvc</artifactId>
                            </dependency>
                            <!-- MCP Client -->
                            <dependency>
                                <groupId>org.springframework.ai</groupId>
                                <artifactId>spring-ai-starter-mcp-client</artifactId>
                            </dependency>
                            """);
                }
                break;

            case "bootstrap":
                dependencies.append("""
                        <!-- Spring Boot Starter -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter</artifactId>
                        </dependency>
                        <!-- Spring Boot Actuator -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-actuator</artifactId>
                        </dependency>
                        <!-- Spring Boot DevTools -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-devtools</artifactId>
                            <optional>true</optional>
                        </dependency>
                        <!-- Test -->
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-test</artifactId>
                            <scope>test</scope>
                        </dependency>
                        """);

                if (config.nacosEnabled()) {
                    dependencies.append("""
                            <!-- Nacos Config -->
                            <dependency>
                                <groupId>com.alibaba.cloud</groupId>
                                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                            </dependency>
                            """);
                }
                break;
        }

        boolean isBootstrap = "bootstrap".equals(moduleType);
        String packaging = isBootstrap ? "jar" : "jar";
        String bootPlugin = isBootstrap ? """
                <!-- Spring Boot Maven Plugin -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <configuration>
                        <excludes>
                            <exclude>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                            </exclude>
                        </excludes>
                    </configuration>
                </plugin>
                """ : "";

        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                         https://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>

                    <parent>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${project.artifactId}</artifactId>
                        <version>${project.version}</version>
                    </parent>

                    <artifactId>${module.artifactId}</artifactId>
                    <packaging>${packaging}</packaging>

                    <dependencies>
                ${deps}
                    </dependencies>

                    <build>
                        <plugins>
                ${boot.plugin}
                        </plugins>
                    </build>
                </project>
                """
                .replace("${module.artifactId}", moduleDirName)
                .replace("${packaging}", packaging)
                .replace("${deps}", dependencies.toString())
                .replace("${boot.plugin}", bootPlugin);
    }
}
